name: Test workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jest tests
    defaults:
      run:
        working-directory: ./www
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and collect coverage
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test --collectCoverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
